- name: Generate grafana.ini
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_dir }}/config/grafana.ini"

- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_dir }}/docker-compose.yml"

- name: Start Grafana
  command: docker compose up -d
  args:
    chdir: "{{ grafana_dir }}"